const responseObj = {
	"hello": "Hey ! How are you doing,press 1 to se what I am capable off ?",
	"hey": "Hey! What's Up, I am Sir Syed University Chat-bot,press 1 to se what I am capable off?",
	"hi":"Hi, I am Sir Syed University Chat-bot,press 1 to se what I am capable off?",
	"how are you":"I am fine,what about you?",
	"When new batch start?":"New batch start on october-2023",
	"what are my semester courses?":"you can find this info on course enrollment page",
	"where sir syed is located":"Sir Syed University Located on:ST-16 Main University Rd, Block 5 Gulshan-e-Iqbal, Karachi, Karachi City, Sindh",
	"where sir syed is located":"ST-16 Main University Rd, Block 5 Gulshan-e-Iqbal, Karachi, Karachi City, Sindh",
	"where university is located":"ST-16 Main Universitengineeringy Rd, Block 5 Gulshan-e-Iqbal, Karachi, Karachi City, Sindh",
	"how much percentage is required to get admission in software ":"Based on previou merit 65%",
	"which degree sir syed give":"PEC and HEC recognized",
	"1":"You can Ask Following Questions to me:::When new batch start?::what are my semester courses?::where sir syed is located::how much percentage is required to get admission in software",
	"today": new Date().toDateString(),
	"time": new Date().toLocaleTimeString(),
  };